<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Login extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Gender_model');

        $this->load->model('City_model');
        $data['all_genders'] = $this->Gender_model->get_all_genders();
        $data['all_cities'] = $this->City_model->get_all_cities();
        
        //$data['_view'] = 'login/index';
       // $this->load->view('layouts/main',$data);
    } 

    /*
     * Listing of acces
     */
    function index()
    {
        $this->load->view("login");
        if($this->session->userdata("auth") != false){

            redirect("Dashboard/index");
        }
    }
    function connect(){
        $user = $this->User_model->connect($this->input->post("email"),$this->input->post("password"));
       
        if(isset($user[0])){
            $this->session->set_userdata("auth",$user[0]);
            redirect("dashboard/index");
        }else{
            redirect("login/index");
        }
    }
    function logout(){
        
        $this->session->unset_userdata(["auth"]);
        $this->session->sess_destroy();
        redirect("Login/index");
    }
   
}